import { NextResponse } from "next/server"
import type { Bridge, ApiResponse } from "@/types/bridge"

/**
 * Bridges API Endpoint
 * 
 * Provides comprehensive bridge data including status, supported chains, tokens,
 * fees, and performance metrics. This endpoint serves as the primary data source
 * for bridge comparison and analysis.
 * 
 * @returns {Promise<NextResponse>} JSON response with array of bridge data
 */

// Mock bridge data - in production, this would come from your data fetchers
// Contains 46 bridges total: 43 active, 0 paused, 3 inactive
const mockBridgeData: Bridge[] = [
  {
    id: "1",
    name: "Stargate Finance",
    status: "active",
    fromChains: ["Ethereum", "Arbitrum", "Polygon", "Avalanche", "BSC"],
    toChains: ["Ethereum", "Arbitrum", "Polygon", "Avalanche", "BSC"],
    supportedTokens: ["USDC", "USDT", "ETH", "STG"],
    transferSpeed: "5-15 mins",
    fee: "0.06% - 0.1%",
    link: "https://stargate.finance",
    tvl: "$800M",  // adjusted down based on trends
    volume24h: "$7M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Hop Protocol",
    status: "active",
    fromChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon"],
    toChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon"],
    supportedTokens: ["ETH", "USDC", "USDT", "DAI", "MATIC"],
    transferSpeed: "10-30 mins",
    fee: "0.04% - 0.2%",
    link: "https://hop.exchange",
    tvl: "$50M",  // significantly declined
    volume24h: "$0.4M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Synapse Protocol",
    status: "active",
    fromChains: ["Ethereum", "Arbitrum", "Avalanche", "BSC", "Polygon"],
    toChains: ["Ethereum", "Arbitrum", "Avalanche", "BSC", "Polygon"],
    supportedTokens: ["ETH", "USDC", "USDT", "DAI", "SYN"],
    transferSpeed: "3-10 mins",
    fee: "0.05% - 0.15%",
    link: "https://synapseprotocol.com",
    tvl: "$200M",
    volume24h: "$0.03M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Multichain",
    status: "active",
    fromChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Fantom"],
    toChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Fantom"],
    supportedTokens: ["ETH", "USDC", "USDT", "DAI", "BTC"],
    transferSpeed: "10-20 mins",
    fee: "0.1% - 0.3%",
    link: "https://multichain.org",
    tvl: "$0",
    volume24h: "$0",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Wormhole",
    status: "active",
    fromChains: ["Ethereum", "Solana", "BSC", "Polygon", "Avalanche"],
    toChains: ["Ethereum", "Solana", "BSC", "Polygon", "Avalanche"],
    supportedTokens: ["ETH", "SOL", "USDC", "USDT"],
    transferSpeed: "15-30 mins",
    fee: "0.1% - 0.25%",
    link: "https://wormhole.com",
    tvl: "$1B",  // aggregated/estimated from portal/bridge data
    volume24h: "$17M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Celer cBridge",
    status: "active",
    fromChains: ["Ethereum", "Arbitrum", "Polygon", "BSC", "Avalanche"],
    toChains: ["Ethereum", "Arbitrum", "Polygon", "BSC", "Avalanche"],
    supportedTokens: ["ETH", "USDC", "USDT", "DAI", "CELR"],
    transferSpeed: "5-20 mins",
    fee: "0.04% - 0.12%",
    link: "https://cbridge.celer.network",
    tvl: "$200M",
    volume24h: "$10M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "7",
    name: "Across Protocol",
    status: "active",
    fromChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon"],
    toChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon"],
    supportedTokens: ["ETH", "USDC", "DAI", "ACX"],
    transferSpeed: "2-5 mins",
    fee: "0.02% - 0.08%",
    link: "https://across.to",
    tvl: "$500M",
    volume24h: "$30M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "8",
    name: "Allbridge",
    status: "active",
    fromChains: ["Ethereum", "Solana", "BSC", "Polygon", "Avalanche"],
    toChains: ["Ethereum", "Solana", "BSC", "Polygon", "Avalanche"],
    supportedTokens: ["ETH", "SOL", "USDC", "USDT", "ABR"],
    transferSpeed: "10-25 mins",
    fee: "0.1% - 0.3%",
    link: "https://allbridge.io",
    tvl: "$100M",
    volume24h: "$5M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "9",
    name: "Orbiter Finance",
    status: "active",
    fromChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "zkSync"],
    toChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "zkSync"],
    supportedTokens: ["ETH", "USDC", "USDT", "DAI"],
    transferSpeed: "3-8 mins",
    fee: "0.05% - 0.15%",
    link: "https://orbiter.finance",
    tvl: "$300M",
    volume24h: "$15M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "10",
    name: "Li.Fi",
    status: "active",
    fromChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "BSC"],
    toChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "BSC"],
    supportedTokens: ["ETH", "USDC", "USDT", "DAI", "MATIC"],
    transferSpeed: "5-15 mins",
    fee: "0.1% - 0.25%",
    link: "https://li.fi",
    tvl: "$400M",
    volume24h: "$20M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "11",
    name: "Hyphen",
    status: "active",
    fromChains: ["Ethereum", "Polygon", "Avalanche", "BSC"],
    toChains: ["Ethereum", "Polygon", "Avalanche", "BSC"],
    supportedTokens: ["ETH", "USDC", "USDT", "DAI"],
    transferSpeed: "8-20 mins",
    fee: "0.1% - 0.2%",
    link: "https://hyphen.biconomy.io",
    tvl: "$50M",
    volume24h: "$2M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "12",
    name: "Connext",
    status: "active",
    fromChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "BSC"],
    toChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "BSC"],
    supportedTokens: ["ETH", "USDC", "DAI", "NEXT"],
    transferSpeed: "10-30 mins",
    fee: "0.05% - 0.15%",
    link: "https://connext.network",
    tvl: "$80M",
    volume24h: "$3M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "13",
    name: "deBridge",
    status: "active",
    fromChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Arbitrum"],
    toChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Arbitrum"],
    supportedTokens: ["ETH", "USDC", "USDT", "DAI", "DBR"],
    transferSpeed: "5-15 mins",
    fee: "0.1% - 0.3%",
    link: "https://debridge.finance",
    tvl: "$150M",
    volume24h: "$5M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "14",
    name: "Axelar",
    status: "active",
    fromChains: ["Ethereum", "Avalanche", "Polygon", "Cosmos", "Terra"],
    toChains: ["Ethereum", "Avalanche", "Polygon", "Cosmos", "Terra"],
    supportedTokens: ["ETH", "USDC", "USDT", "AXL"],
    transferSpeed: "10-25 mins",
    fee: "0.1% - 0.2%",
    link: "https://axelar.network",
    tvl: "$300M",
    volume24h: "$10M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "15",
    name: "Omo Swap",
    status: "active",
    fromChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Arbitrum"],
    toChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Arbitrum"],
    supportedTokens: ["ETH", "USDC", "USDT", "O3"],
    transferSpeed: "12-28 mins",
    fee: "0.12% - 0.28%",
    link: "https://app.omoswap.xyz/",
    tvl: "$2M",
    volume24h: "$0.0004M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "16",
    name: "Symbiosis Finance",
    status: "active",
    fromChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Bitcoin", "Solana"],
    toChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Bitcoin", "Solana"],
    supportedTokens: ["ETH", "USDC", "USDT", "BTC", "SOL"],
    transferSpeed: "5-20 mins",
    fee: "0.1% - 0.2%",
    link: "https://symbiosis.finance",
    tvl: "$250M",
    volume24h: "$8M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "17",
    name: "Rhino.Fi",
    status: "active",
    fromChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "zkSync"],
    toChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "zkSync"],
    supportedTokens: ["ETH", "USDC", "USDT", "DAI"],
    transferSpeed: "3-10 mins",
    fee: "0.05% - 0.15%",
    link: "https://rhino.fi",
    tvl: "$200M",
    volume24h: "$6M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "18",
    name: "THORChain",
    status: "active",
    fromChains: ["Bitcoin", "Ethereum", "BSC", "Avalanche", "Cosmos"],
    toChains: ["Bitcoin", "Ethereum", "BSC", "Avalanche", "Cosmos"],
    supportedTokens: ["BTC", "ETH", "RUNE", "USDC", "USDT"],
    transferSpeed: "10-30 mins",
    fee: "0.1% - 0.3%",
    link: "https://thorchain.org",
    tvl: "$400M",
    volume24h: "$20M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "19",
    name: "Arbitrum Bridge",
    status: "active",
    fromChains: ["Ethereum"],
    toChains: ["Arbitrum"],
    supportedTokens: ["ETH", "USDC", "USDT", "DAI"],
    transferSpeed: "7 days withdrawal",
    fee: "0.01% - 0.05%",
    link: "https://bridge.arbitrum.io",
    tvl: "$4.2B",
    volume24h: "$60M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "20",
    name: "Polygon Bridge",
    status: "active",
    fromChains: ["Ethereum"],
    toChains: ["Polygon"],
    supportedTokens: ["ETH", "USDC", "USDT", "DAI", "MATIC"],
    transferSpeed: "10-30 mins",
    fee: "0.01% - 0.1%",
    link: "https://portal.polygon.technology/bridge",
    tvl: "$1.2B",
    volume24h: "$30M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "21",
    name: "BNB Chain Bridge",
    status: "active",
    fromChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon"],
    toChains: ["BSC"],
    supportedTokens: ["ETH", "USDC", "USDT", "BNB"],
    transferSpeed: "5-15 mins",
    fee: "0.05% - 0.15%",
    link: "https://www.bnbchain.org/en/bnb-chain-bridge",
    tvl: "$700M",
    volume24h: "$25M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "22",
    name: "Avalanche Bridge",
    status: "active",
    fromChains: ["Ethereum", "Bitcoin"],
    toChains: ["Avalanche"],
    supportedTokens: ["ETH", "BTC", "USDC", "USDT", "AVAX"],
    transferSpeed: "5-10 mins",
    fee: "0.1% - 0.2%",
    link: "https://core.app/bridge",
    tvl: "$600M",
    volume24h: "$20M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "23",
    name: "Jumper",
    status: "active",
    fromChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "BSC", "Avalanche"],
    toChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "BSC", "Avalanche"],
    supportedTokens: ["ETH", "USDC", "USDT", "DAI"],
    transferSpeed: "3-15 mins",
    fee: "0.05% - 0.2%",
    link: "https://jumper.exchange",
    tvl: "$250M",
    volume24h: "$12M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "24",
    name: "Meson",
    status: "active",
    fromChains: ["Ethereum", "BSC", "Polygon", "Arbitrum"],
    toChains: ["Ethereum", "BSC", "Polygon", "Arbitrum"],
    supportedTokens: ["USDC", "USDT", "ETH"],
    transferSpeed: "1-5 mins",
    fee: "0.02% - 0.1%",
    link: "https://meson.fi",
    tvl: "$200M",
    volume24h: "$6M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "25",
    name: "Transporter",
    status: "active",
    fromChains: ["Ethereum", "Arbitrum", "Optimism", "Base"],
    toChains: ["Ethereum", "Arbitrum", "Optimism", "Base"],
    supportedTokens: ["ETH", "USDC", "USDT"],
    transferSpeed: "5-20 mins",
    fee: "0.05% - 0.15%",
    link: "https://transporter.io",
    tvl: "$150M",
    volume24h: "$5M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "26",
    name: "Sui Bridge",
    status: "active",
    fromChains: ["Ethereum"],
    toChains: ["Sui"],
    supportedTokens: ["ETH", "USDC", "USDT"],
    transferSpeed: "10-25 mins",
    fee: "0.1% - 0.25%",
    link: "https://bridge.sui.io",
    tvl: "$120M",
    volume24h: "$4M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "27",
    name: "Rango",
    status: "active",
    fromChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Fantom"],
    toChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Fantom"],
    supportedTokens: ["ETH", "USDC", "USDT", "DAI"],
    transferSpeed: "5-15 mins",
    fee: "0.1% - 0.3%",
    link: "https://rango.exchange",
    tvl: "$90M",
    volume24h: "$3M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "28",
    name: "Rubic",
    status: "active",
    fromChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "zkSync"],
    toChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "zkSync"],
    supportedTokens: ["ETH", "USDC", "USDT", "DAI"],
    transferSpeed: "3-10 mins",
    fee: "0.05% - 0.2%",
    link: "https://app.rubic.exchange/",
    tvl: "$70M",
    volume24h: "$2M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "29",
    name: "Defiway Bridge",
    status: "active",
    fromChains: ["Ethereum", "BSC", "Polygon", "TON"],
    toChains: ["Ethereum", "BSC", "Polygon", "TON"],
    supportedTokens: ["ETH", "USDC", "USDT", "TON"],
    transferSpeed: "5-20 mins",
    fee: "0.1% - 0.25%",
    link: "https://defiway.com/bridge",
    tvl: "$60M",
    volume24h: "$1.5M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "30",
    name: "TON Bridge",
    status: "active",
    fromChains: ["Ethereum", "BSC", "Solana"],
    toChains: ["TON"],
    supportedTokens: ["ETH", "USDC", "USDT", "TON"],
    transferSpeed: "10-30 mins",
    fee: "0.05% - 0.15%",
    link: "https://bridge-v3.ton.org",
    tvl: "$50M",
    volume24h: "$1M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "31",
    name: "LayerZero",
    status: "active",
    fromChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Solana", "Arbitrum", "Optimism"],
    toChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Solana", "Arbitrum", "Optimism"],
    supportedTokens: ["ETH", "USDC", "USDT", "ZRO"],
    transferSpeed: "1-5 mins",
    fee: "0.01% - 0.05%",
    link: "https://layerzero.network",
    tvl: "$1B",
    volume24h: "$40M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "32",
    name: "Router Protocol",
    status: "active",
    fromChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Fantom"],
    toChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Fantom"],
    supportedTokens: ["ETH", "USDC", "USDT", "ROUTE"],
    transferSpeed: "5-15 mins",
    fee: "0.1% - 0.2%",
    link: "https://app.routerprotocol.com/",
    tvl: "$200M",
    volume24h: "$8M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "35",
    name: "Wrap Protocol",
    status: "active",
    fromChains: ["Ethereum", "Tezos"],
    toChains: ["Ethereum", "Tezos"],
    supportedTokens: ["ETH", "XTZ", "USDC"],
    transferSpeed: "10-25 mins",
    fee: "0.1% - 0.25%",
    link: "https://www.benderlabs.io/wrap",
    tvl: "$150M",
    volume24h: "$4M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "36",
    name: "LayerSwap",
    status: "active",
    fromChains: ["Ethereum", "BSC", "Polygon", "Solana"],
    toChains: ["Ethereum", "BSC", "Polygon", "Solana"],
    supportedTokens: ["ETH", "USDC", "USDT", "SOL"],
    transferSpeed: "5-20 mins",
    fee: "0.05% - 0.15%",
    link: "https://layerswap.io",
    tvl: "$140M",
    volume24h: "$4M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "37",
    name: "Nomad",
    status: "inactive",
    fromChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon"],
    toChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon"],
    supportedTokens: ["ETH", "USDC", "DAI"],
    transferSpeed: "3-12 mins",
    fee: "0.03% - 0.1%",
    link: "https://nomad.xyz",
    tvl: "NIL",
    volume24h: "NIL",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "38",
    name: "Hyperlane",
    status: "active",
    fromChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Cosmos"],
    toChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Cosmos"],
    supportedTokens: ["ETH", "USDC", "USDT"],
    transferSpeed: "5-15 mins",
    fee: "0.1% - 0.2%",
    link: "https://nexus.hyperlane.xyz",
    tvl: "$120M",
    volume24h: "$3M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "39",
    name: "Socket Tech",
    status: "inactive",
    fromChains: ["Ethereum", "Arbitrum", "Optimism", "Base", "zkSync"],
    toChains: ["Ethereum", "Arbitrum", "Optimism", "Base", "zkSync"],
    supportedTokens: ["ETH", "USDC", "USDT", "DAI"],
    transferSpeed: "2-10 mins",
    fee: "0.05% - 0.12%",
    link: "https://www.socket.tech",
    tvl: "NIL",
    volume24h: "NIL",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "40",
    name: "Mayan Finance",
    status: "active",
    fromChains: ["Solana", "Ethereum", "BSC"],
    toChains: ["Solana", "Ethereum", "BSC"],
    supportedTokens: ["SOL", "ETH", "USDC"],
    transferSpeed: "1-5 mins",
    fee: "0.02% - 0.08%",
    link: "https://swap.mayan.finance/",
    tvl: "$100M",
    volume24h: "$2M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "41",
    name: "Squid",
    status: "active",
    fromChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Arbitrum"],
    toChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Arbitrum"],
    supportedTokens: ["ETH", "USDC", "USDT", "DAI"],
    transferSpeed: "3-10 mins",
    fee: "0.05% - 0.15%",
    link: "https://app.squidrouter.com/",
    tvl: "$100M",
    volume24h: "$2M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "42",
    name: "Hashport",
    status: "active",
    fromChains: ["Ethereum", "Polygon", "Avalanche", "Cardano"],
    toChains: ["Ethereum", "Polygon", "Avalanche", "Cardano"],
    supportedTokens: ["ETH", "USDC", "ADA"],
    transferSpeed: "10-20 mins",
    fee: "0.1% - 0.25%",
    link: "https://app.hashport.network/",
    tvl: "$90M",
    volume24h: "$2M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "43",
    name: "Outerbridge",
    status: "inactive",
    fromChains: ["Ethereum", "BSC", "Polygon"],
    toChains: ["Ethereum", "BSC", "Polygon"],
    supportedTokens: ["ETH", "USDC", "USDT"],
    transferSpeed: "5-15 mins",
    fee: "0.08% - 0.18%",
    link: "https://outerbridge.io/",
    tvl: "NIL",
    volume24h: "NIL",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "44",
    name: "Orbit Bridge",
    status: "active",
    fromChains: ["Ethereum", "BSC", "Polygon", "Klaytn"],
    toChains: ["Ethereum", "BSC", "Polygon", "Klaytn"],
    supportedTokens: ["ETH", "USDC", "KLAY"],
    transferSpeed: "8-20 mins",
    fee: "0.1% - 0.2%",
    link: "https://bridge.orbitchain.io/",
    tvl: "$70M",
    volume24h: "$1.5M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "45",
    name: "Owlto Finance",
    status: "active",
    fromChains: ["Ethereum", "Arbitrum", "Optimism", "Base"],
    toChains: ["Ethereum", "Arbitrum", "Optimism", "Base"],
    supportedTokens: ["ETH", "USDC", "USDT"],
    transferSpeed: "3-10 mins",
    fee: "0.05% - 0.15%",
    link: "https://owlto.finance/",
    tvl: "$200M",
    volume24h: "$10M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "46",
    name: "Wanchain Bridge",
    status: "active",
    fromChains: ["Ethereum", "BSC", "Polygon"],
    toChains: ["Ethereum", "BSC", "Polygon", "Wanchain"],
    supportedTokens: ["ETH", "USDC", "WAN"],
    transferSpeed: "10-25 mins",
    fee: "0.1% - 0.3%",
    link: "https://bridge.wanchain.org",
    tvl: "$60M",
    volume24h: "$1M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "47",
    name: "Altitude",
    status: "active",
    fromChains: ["Ethereum", "Avalanche", "Polygon"],
    toChains: ["Ethereum", "Avalanche", "Polygon"],
    supportedTokens: ["ETH", "USDC", "USDT"],
    transferSpeed: "5-15 mins",
    fee: "0.06% - 0.12%",
    link: "https://altitude.fi",
    tvl: "$50M",
    volume24h: "$1M",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "48",
    name: "Chainspot",
    status: "active",
    fromChains: ["Ethereum", "BSC", "Polygon", "Arbitrum", "Optimism"],
    toChains: ["Ethereum", "BSC", "Polygon", "Arbitrum", "Optimism"],
    supportedTokens: ["ETH", "USDC", "USDT", "DAI"],
    transferSpeed: "4-12 mins",
    fee: "0.04% - 0.1%",
    link: "https://app.chainspot.io",
    tvl: "$40M",
    volume24h: "$0.8M",
    lastUpdated: new Date().toISOString(),
  },
];

export async function GET() {
  try {
    // Simulate API processing delay for realistic loading states
    await new Promise((resolve) => setTimeout(resolve, 100))

    // Return successful response with bridge data
    const response: ApiResponse<Bridge[]> = {
      data: mockBridgeData, // Array of 46 bridge objects
      success: true,
      lastUpdated: new Date().toISOString(),
    }

    return NextResponse.json(response)
  } catch (error) {
    // Handle any errors and return error response
    const errorResponse: ApiResponse<Bridge[]> = {
      data: [],
      success: false,
      lastUpdated: new Date().toISOString(),
      error: "Failed to fetch bridge data",
    }

    return NextResponse.json(errorResponse, { status: 500 })
  }
}