/**
 * Bridge Static Configuration
 *
 * Single source of truth for all bridge metadata that changes infrequently:
 * supported chains, tokens, fees, speed, and links.
 *
 * Live fields (tvl, volume24h) are fetched from DeFiLlama and merged at
 * request time in the route handlers. Update this file manually when a
 * bridge adds chain support, changes fees, or changes status.
 *
 * defillamaSlug: the protocol slug used in api.llama.fi/tvl/{slug}
 *   - string  → live TVL + volume fetched from DeFiLlama daily
 *   - null    → no DeFiLlama listing; staticTvl/staticVolume24h used instead
 *
 * Last reviewed: April 2026
 */

export interface BridgeConfig {
    id: string
    name: string
    status: "active" | "paused" | "inactive"
    fromChains: string[]
    toChains: string[]
    supportedTokens: string[]
    transferSpeed: string
    fee: string
    link: string
    defillamaSlug: string | null
    staticTvl: string
    staticVolume24h: string
    bridgeType: "Lock-Mint" | "Liquidity Pool" | "Intent-Based" | "Native"
    overrideChains?: boolean
}

export const BRIDGE_CONFIG: BridgeConfig[] = [
        // ─── Priority 1: DeFiLlama listed + highest volume (top 20 new list) ───────
{
        id: "1",
        name: "USDT0",
        status: "active",
        fromChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "BSC", "Base"],
        toChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "BSC", "Base"],
        supportedTokens: ["USDT", "USDT0"],
        transferSpeed: "2-5 mins",
        fee: "0.01% - 0.05%",
        link: "https://usdt0.to",
        defillamaSlug: "usdt0",
        bridgeType: "Lock-Mint",
        staticTvl: "$3.7B",
        staticVolume24h: "$300M",
    },
    {
        id: "2",
        name: "Polygon PoS Bridge",
        status: "active",
        fromChains: ["Ethereum"],
        toChains: ["Polygon"],
        supportedTokens: ["ETH", "USDC", "USDT", "DAI", "MATIC"],
        transferSpeed: "7-10 mins",
        fee: "0.1%",
        link: "https://portal.polygon.technology/",
        defillamaSlug: "polygon-bridge",
        bridgeType: "Native",
        staticTvl: "$2.5B",
        staticVolume24h: "$12M",
        overrideChains: true,
    },
    {
        id: "3",
        name: "Interport Finance",
        status: "active",
        fromChains: ["Ethereum", "Arbitrum", "Optimism", "BSC", "Polygon", "Base"],
        toChains: ["Ethereum", "Arbitrum", "Optimism", "BSC", "Polygon", "Base"],
        supportedTokens: ["USDC", "USDT", "DAI", "ETH"],
        transferSpeed: "2-5 mins",
        fee: "0.05% - 0.1%",
        link: "https://app.interport.fi",
        defillamaSlug: "interport-finance",
        bridgeType: "Intent-Based",
        staticTvl: "$7M",
        staticVolume24h: "$10M",
    },
    {
        id: "4",
        name: "Arbitrum Bridge",
        status: "active",
        fromChains: ["Ethereum"],
        toChains: ["Arbitrum"],
        supportedTokens: ["ETH", "USDC", "USDT", "DAI"],
        transferSpeed: "10-15 mins",
        fee: "0.05%",
        link: "https://portal.arbitrum.io/bridge",
        defillamaSlug: "arbitrum-bridge",
        bridgeType: "Native",
        staticTvl: "$3.5B",
        staticVolume24h: "$4M",
        overrideChains: true,
    },
    {
        id: "5",
        name: "Butter Network",
        status: "active",
        fromChains: ["Ethereum", "BSC", "Polygon", "Base", "Arbitrum", "Optimism"],
        toChains: ["Ethereum", "BSC", "Polygon", "Base", "Arbitrum", "Optimism"],
        supportedTokens: ["ETH", "USDC", "USDT"],
        transferSpeed: "3-8 mins",
        fee: "0.03% - 0.08%",
        link: "https://www.butterswap.io/swap",
        defillamaSlug: "butter-network",
        bridgeType: "Lock-Mint",
        staticTvl: "$1.5M",
        staticVolume24h: "$3M",
    },
    {
        id: "6",
        name: "Optimism Bridge",
        status: "active",
        fromChains: ["Ethereum"],
        toChains: ["Optimism"],
        supportedTokens: ["ETH", "USDC", "USDT", "DAI", "OP"],
        transferSpeed: "5-10 mins",
        fee: "0.05%",
        link: "https://app.optimism.io/bridge",
        defillamaSlug: "optimism-bridge",
        bridgeType: "Native",
        staticTvl: "$530M",
        staticVolume24h: "$2M",
        overrideChains: true,
    },
    {
        id: "7",
        name: "Mantle Bridge",
        status: "active",
        fromChains: ["Ethereum"],
        toChains: ["Mantle"],
        supportedTokens: ["ETH", "USDC", "USDT", "MNT"],
        transferSpeed: "10 mins",
        fee: "0.05%",
        link: "https://app.mantle.xyz/bridge",
        defillamaSlug: "mantle-bridge",
        bridgeType: "Native",
        staticTvl: "$260M",
        staticVolume24h: "$1.5M",
        overrideChains: true,
    },
    {
        id: "8",
        name: "Garden",
        status: "active",
        fromChains: ["Bitcoin", "Ethereum", "Arbitrum"],
        toChains: ["Bitcoin", "Ethereum", "Arbitrum"],
        supportedTokens: ["BTC", "WBTC"],
        transferSpeed: "5-10 mins",
        fee: "0.1% - 0.2%",
        link: "https://app.garden.finance",
        defillamaSlug: "garden",
        bridgeType: "Lock-Mint",
        staticTvl: "$10M",
        staticVolume24h: "$1.2M",
    },
    {
        id: "9",
        name: "Meson",
        status: "active",
        fromChains: ["Ethereum", "BSC", "Polygon", "Base", "Arbitrum", "Optimism"],
        toChains: ["Ethereum", "BSC", "Polygon", "Base", "Arbitrum", "Optimism"],
        supportedTokens: ["USDC", "USDT"],
        transferSpeed: "1-2 mins",
        fee: "0.03%",
        link: "https://meson.fi",
        defillamaSlug: "meson",
        bridgeType: "Intent-Based",
        staticTvl: "$1.3M",
        staticVolume24h: "$1.1M",
    },
    {
        id: "10",
        name: "Aori",
        status: "active",
        fromChains: ["Ethereum", "Arbitrum", "Optimism"],
        toChains: ["Ethereum", "Arbitrum", "Optimism"],
        supportedTokens: ["USDC", "USDT", "DAI"],
        transferSpeed: "2-5 mins",
        fee: "0.02%",
        link: "https://aori.io",
        defillamaSlug: "aori",
        bridgeType: "Lock-Mint",
        staticTvl: "$5M",
        staticVolume24h: "$0.9M",
    },
    {
        id: "11",
        name: "Teleswap",
        status: "active",
        fromChains: ["Bitcoin", "Ethereum", "Polygon", "BSC"],
        toChains: ["Bitcoin", "Ethereum", "Polygon", "BSC"],
        supportedTokens: ["BTC", "ETH", "USDC"],
        transferSpeed: "10-20 mins",
        fee: "0.08% - 0.15%",
        link: "https://teleswap.xyz",
        defillamaSlug: "teleswap",
        bridgeType: "Lock-Mint",
        staticTvl: "$136K",
        staticVolume24h: "$0.5M",
    },
    {
        id: "12",
        name: "Cashmere",
        status: "active",
        fromChains: ["Aptos, Ethereum", "BSC", "Polygon", "Arbitrum", "Optimism"],
        toChains: ["Aptos, Ethereum", "BSC", "Polygon", "Arbitrum", "Optimism"],
        supportedTokens: ["USDC", "USDT", "ETH"],
        transferSpeed: "5-15 mins",
        fee: "0.05% - 0.12%",
        link: "https://app.cashmere.exchange",
        defillamaSlug: "cashmere",
        bridgeType: "Lock-Mint",
        staticTvl: "$1M",
        staticVolume24h: "$0.4M",
    },


    
    // ─── Priority 2: DeFiLlama listed existing bridges ─────────────────────────
{
        id: "13",
        name: "Stargate Finance",
        status: "active",
        fromChains: ["Ethereum", "Arbitrum", "Polygon", "Avalanche", "BSC"],
        toChains: ["Ethereum", "Arbitrum", "Polygon", "Avalanche", "BSC"],
        supportedTokens: ["USDC", "USDT", "ETH", "STG"],
        transferSpeed: "5-15 mins",
        fee: "0.06% - 0.1%",
        link: "https://stargate.finance",
        defillamaSlug: "stargate-v2",
        bridgeType: "Liquidity Pool",
        staticTvl: "$800M",
        staticVolume24h: "$7M",
    },
    {
        id: "14",
        name: "Hop Protocol",
        status: "active",
        fromChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon"],
        toChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon"],
        supportedTokens: ["ETH", "USDC", "USDT", "DAI", "MATIC"],
        transferSpeed: "10-30 mins",
        fee: "0.04% - 0.2%",
        link: "https://hop.exchange",
        defillamaSlug: "hop-protocol",
        bridgeType: "Liquidity Pool",
        staticTvl: "$50M",
        staticVolume24h: "$0.4M",
    },
    {
        id: "15",
        name: "Synapse Protocol",
        status: "active",
        fromChains: ["Ethereum", "Arbitrum", "Avalanche", "BSC", "Polygon"],
        toChains: ["Ethereum", "Arbitrum", "Avalanche", "BSC", "Polygon"],
        supportedTokens: ["ETH", "USDC", "USDT", "DAI", "SYN"],
        transferSpeed: "3-10 mins",
        fee: "0.05% - 0.15%",
        link: "https://bridge.synapseprotocol.com",
        defillamaSlug: "synapse",
        bridgeType: "Liquidity Pool",
        staticTvl: "$200M",
        staticVolume24h: "$0.03M",
    },
    {
        id: "16",
        name: "Portal (Wormhole)",
        status: "active",
        fromChains: ["Ethereum", "Solana", "BSC", "Polygon", "Avalanche"],
        toChains: ["Ethereum", "Solana", "BSC", "Polygon", "Avalanche"],
        supportedTokens: ["ETH", "SOL", "USDC", "USDT"],
        transferSpeed: "15-30 mins",
        fee: "0.1% - 0.25%",
        link: "https://portalbridge.com",
        defillamaSlug: "portal",
        bridgeType: "Lock-Mint",
        staticTvl: "$1B",
        staticVolume24h: "$17M",
    },
    {
        id: "17",
        name: "Celer cBridge",
        status: "active",
        fromChains: ["Ethereum", "Arbitrum", "Polygon", "BSC", "Avalanche"],
        toChains: ["Ethereum", "Arbitrum", "Polygon", "BSC", "Avalanche"],
        supportedTokens: ["ETH", "USDC", "USDT", "DAI", "CELR"],
        transferSpeed: "5-20 mins",
        fee: "0.04% - 0.12%",
        link: "https://cbridge.celer.network",
        defillamaSlug: "cbridge",
        bridgeType: "Liquidity Pool",
        staticTvl: "$200M",
        staticVolume24h: "$10M",
    },
    {
        id: "18",
        name: "Across Protocol",
        status: "active",
        fromChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon"],
        toChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon"],
        supportedTokens: ["ETH", "USDC", "DAI", "ACX"],
        transferSpeed: "2-5 mins",
        fee: "0.02% - 0.08%",
        link: "https://app.across.to/bridge-and-swap?",
        defillamaSlug: "across-protocol",
        bridgeType: "Intent-Based",
        staticTvl: "$500M",
        staticVolume24h: "$30M",
    },
    {
        id: "19",
        name: "Allbridge",
        status: "active",
        fromChains: ["Ethereum", "Solana", "BSC", "Polygon", "Avalanche"],
        toChains: ["Ethereum", "Solana", "BSC", "Polygon", "Avalanche"],
        supportedTokens: ["ETH", "SOL", "USDC", "USDT", "ABR"],
        transferSpeed: "10-25 mins",
        fee: "0.1% - 0.3%",
        link: "https://app.allbridge.io/bridge",
        defillamaSlug: "allbridge-classic",
        bridgeType: "Liquidity Pool",
        staticTvl: "$100M",
        staticVolume24h: "$5M",
    },
    {
        id: "20",
        name: "Orbiter Finance",
        status: "active",
        fromChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "zkSync"],
        toChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "zkSync"],
        supportedTokens: ["ETH", "USDC", "USDT", "DAI"],
        transferSpeed: "3-8 mins",
        fee: "0.05% - 0.15%",
        link: "https://orbiter.finance",
        defillamaSlug: "orbiter-finance",
        bridgeType: "Lock-Mint",
        staticTvl: "$300M",
        staticVolume24h: "$15M",
    },
    {
        id: "21",
        name: "Jumper Bridge",
        status: "active",
        fromChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "BSC"],
        toChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "BSC"],
        supportedTokens: ["ETH", "USDC", "USDT", "DAI", "MATIC"],
        transferSpeed: "5-15 mins",
        fee: "0.1% - 0.25%",
        link: "https://jumper.xyz/",
        defillamaSlug: "jumper-(li.fi-powered)",
        bridgeType: "Intent-Based",
        staticTvl: "$400M",
        staticVolume24h: "$20M",
    },
    {
        id: "22",
        name: "Connext",
        status: "active",
        fromChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "BSC"],
        toChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "BSC"],
        supportedTokens: ["ETH", "USDC", "DAI", "NEXT"],
        transferSpeed: "10-30 mins",
        fee: "0.05% - 0.15%",
        link: "https://connext.network",
        defillamaSlug: "connext",
        bridgeType: "Liquidity Pool",
        staticTvl: "$80M",
        staticVolume24h: "$3M",
    },
    {
        id: "23",
        name: "deBridge",
        status: "active",
        fromChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Arbitrum"],
        toChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Arbitrum"],
        supportedTokens: ["ETH", "USDC", "USDT", "DAI", "DBR"],
        transferSpeed: "5-15 mins",
        fee: "0.1% - 0.3%",
        link: "https://app.debridge.com",
        defillamaSlug: "debridge",
        bridgeType: "Intent-Based",
        staticTvl: "$150M",
        staticVolume24h: "$5M",
    },
    {
        id: "24",
        name: "Symbiosis Finance",
        status: "active",
        fromChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Bitcoin", "Solana"],
        toChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Bitcoin", "Solana"],
        supportedTokens: ["ETH", "USDC", "USDT", "BTC", "SOL"],
        transferSpeed: "5-20 mins",
        fee: "0.1% - 0.2%",
        link: "https://app.symbiosis.finance/swap",
        defillamaSlug: "symbiosis-finance",
        bridgeType: "Intent-Based",
        staticTvl: "$250M",
        staticVolume24h: "$8M",
    },
    {
        id: "25",
        name: "Rhino.Fi",
        status: "active",
        fromChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "zkSync"],
        toChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "zkSync"],
        supportedTokens: ["ETH", "USDC", "USDT", "DAI"],
        transferSpeed: "3-10 mins",
        fee: "0.05% - 0.15%",
        link: "https://app.rhino.fi/bridge",
        defillamaSlug: "rhino.fi",
        bridgeType: "Lock-Mint",
        staticTvl: "$200M",
        staticVolume24h: "$6M",
    },
    {
        id: "26",
        name: "THORChain",
        status: "active",
        fromChains: ["Bitcoin", "Ethereum", "BSC", "Avalanche"],
        toChains: ["Bitcoin", "Ethereum", "BSC", "Avalanche"],
        supportedTokens: ["BTC", "ETH", "USDC", "RUNE"],
        transferSpeed: "5-15 mins",
        fee: "0.1% - 0.3%",
        link: "https://swap.thorchain.org/swap",
        defillamaSlug: "thorchain",
        bridgeType: "Lock-Mint",
        staticTvl: "$50M",
        staticVolume24h: "$20M",
    },
    {
        id: "27",
        name: "Rainbow Bridge",
        status: "active",
        fromChains: ["Ethereum", "NEAR"],
        toChains: ["Ethereum", "NEAR"],
        supportedTokens: ["ETH", "USDC", "USDT", "NEAR"],
        transferSpeed: "10-30 mins",
        fee: "0.05% - 0.15%",
        link: "https://rainbowbridge.app",
        defillamaSlug: "rainbow-bridge",
        bridgeType: "Lock-Mint",
        staticTvl: "$80M",
        staticVolume24h: "$2M",
    },
    {
        id: "28",
        name: "Ronin Bridge",
        status: "active",
        fromChains: ["Ethereum", "Ronin"],
        toChains: ["Ethereum", "Ronin"],
        supportedTokens: ["ETH", "USDC", "AXS", "RON"],
        transferSpeed: "10-20 mins",
        fee: "0.1% - 0.2%",
        link: "https://app.roninchain.com/bridge",
        defillamaSlug: "ronin",
        bridgeType: "Native",
        staticTvl: "$200M",
        staticVolume24h: "$5M",
    },
    {
        id: "29",
        name: "Gravity Bridge",
        status: "active",
        fromChains: ["Ethereum", "Cosmos"],
        toChains: ["Ethereum", "Cosmos"],
        supportedTokens: ["ETH", "USDC", "GRAV"],
        transferSpeed: "15-30 mins",
        fee: "0.1% - 0.25%",
        link: "https://bridge.blockscape.network",
        defillamaSlug: "gravity-bridge",
        bridgeType: "Lock-Mint",
        staticTvl: "$50M",
        staticVolume24h: "$1M",
    },
    {
        id: "30",
        name: "Router Protocol",
        status: "active",
        fromChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Fantom"],
        toChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Fantom"],
        supportedTokens: ["ETH", "USDC", "USDT", "ROUTE"],
        transferSpeed: "5-15 mins",
        fee: "0.1% - 0.2%",
        link: "https://app.routerprotocol.com/",
        defillamaSlug: "router-protocol",
        bridgeType: "Intent-Based",
        staticTvl: "$200M",
        staticVolume24h: "$8M",
    },
    {
        id: "31",
        name: "Hyperlane",
        status: "active",
        fromChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Cosmos"],
        toChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Cosmos"],
        supportedTokens: ["ETH", "USDC", "USDT"],
        transferSpeed: "5-15 mins",
        fee: "0.1% - 0.2%",
        link: "https://nexus.hyperlane.xyz",
        defillamaSlug: "hyperlane",
        bridgeType: "Lock-Mint",
        staticTvl: "$120M",
        staticVolume24h: "$3M",
    },
    {
        id: "32",
        name: "Mayan Finance",
        status: "active",
        fromChains: ["Solana", "Ethereum", "BSC"],
        toChains: ["Solana", "Ethereum", "BSC"],
        supportedTokens: ["SOL", "ETH", "USDC"],
        transferSpeed: "1-5 mins",
        fee: "0.02% - 0.08%",
        link: "https://swap.mayan.finance/",
        defillamaSlug: "mayan",
        bridgeType: "Lock-Mint",
        staticTvl: "$100M",
        staticVolume24h: "$2M",
    },
    {
        id: "33",
        name: "Orbit Bridge",
        status: "active",
        fromChains: ["Ethereum", "BSC", "Polygon", "Klaytn"],
        toChains: ["Ethereum", "BSC", "Polygon", "Klaytn"],
        supportedTokens: ["ETH", "USDC", "KLAY"],
        transferSpeed: "8-20 mins",
        fee: "0.1% - 0.2%",
        link: "https://bridge.orbitchain.io/",
        defillamaSlug: "orbit-bridge",
        bridgeType: "Lock-Mint",
        staticTvl: "$70M",
        staticVolume24h: "$1.5M",
    },
    {
        id: "34",
        name: "Wanchain Bridge",
        status: "active",
        fromChains: ["Ethereum", "BSC", "Polygon"],
        toChains: ["Ethereum", "BSC", "Polygon", "Wanchain"],
        supportedTokens: ["ETH", "USDC", "WAN"],
        transferSpeed: "10-25 mins",
        fee: "0.1% - 0.3%",
        link: "https://bridge.wanchain.org",
        defillamaSlug: "wan-bridge",
        bridgeType: "Lock-Mint",
        staticTvl: "$60M",
        staticVolume24h: "$1M",
    },


    {
        id: "35",
        name: "Threshold Network",
        status: "active",
        fromChains: ["Bitcoin", "Ethereum", "Arbitrum", "Optimism"],
        toChains: ["Bitcoin", "Ethereum", "Arbitrum", "Optimism"],
        supportedTokens: ["BTC", "tBTC"],
        transferSpeed: "15-30 mins",
        fee: "0.05% - 0.1%",
        link: "https://threshold.network",
        defillamaSlug: "tbtc", 
        bridgeType: "Lock-Mint",
        staticTvl: "$400M",
        staticVolume24h: "$3M",
    },
    {
        id: "36",
        name: "Bungee Exchange",
        status: "active",
        fromChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "BSC"],
        toChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon", "BSC"],
        supportedTokens: ["ETH", "USDC", "USDT", "DAI"],
        transferSpeed: "3-10 mins",
        fee: "0.05% - 0.15%",
        link: "https://www.bungee.exchange",
        defillamaSlug: "bungee-dex", 
        bridgeType: "Intent-Based",
        staticTvl: "$100M",
        staticVolume24h: "$5M",
    },
    {
        id: "37",
        name: "Corebridge",
        status: "active",
        fromChains: ["Ethereum", "BSC", "Avalanche"],
        toChains: ["Ethereum", "BSC", "Avalanche"],
        supportedTokens: ["ETH", "USDC", "USDT"],
        transferSpeed: "10-20 mins",
        fee: "0.1% - 0.25%",
        link: "https://bridge.coredao.org/bridge",
        defillamaSlug: "core-bridge", 
        bridgeType: "Lock-Mint",
        staticTvl: "$30M",
        staticVolume24h: "$1M",
    },
    {
        id: "38",
        name: "Sui Bridge",
        status: "active",
        fromChains: ["Ethereum", "Sui"],
        toChains: ["Ethereum", "Sui"],
        supportedTokens: ["ETH", "USDC", "SUI"],
        transferSpeed: "5-15 mins",
        fee: "0.1% - 0.2%",
        link: "https://bridge.sui.io",
        defillamaSlug: "suibridge", 
        bridgeType: "Native",
        staticTvl: "$150M",
        staticVolume24h: "$5M",
    },
    {
        id: "39",
        name: "Chainspot", 
        status: "active",
        fromChains: ["Ethereum", "BSC", "Polygon", "Arbitrum", "Optimism"],
        toChains: ["Ethereum", "BSC", "Polygon", "Arbitrum", "Optimism"],
        supportedTokens: ["ETH", "USDC", "USDT", "DAI"],
        transferSpeed: "4-12 mins",
        fee: "0.04% - 0.1%",
        link: "https://app.chainspot.io",
        defillamaSlug: "chainspot",
        bridgeType: "Intent-Based",
        staticTvl: "$40M",
        staticVolume24h: "$0.8M",
    },

    
    // ─── Priority 3: No DeFiLlama listing (static only) ────────────────────────
{
        id: "40",
        name: "Relay",
        status: "active",
        fromChains: ["Ethereum", "Arbitrum", "Optimism", "Base"],
        toChains: ["Ethereum", "Arbitrum", "Optimism", "Base"],
        supportedTokens: ["ETH", "USDC", "USDT"],
        transferSpeed: "1-3 mins",
        fee: "0.01% - 0.04%",
        link: "https://relay.link",
        defillamaSlug: null,
        bridgeType: "Lock-Mint",
        staticTvl: "$50M",
        staticVolume24h: "$50M",
    },
    {
        id: "41",
        name: "Gnosis Bridge",
        status: "active",
        fromChains: ["Ethereum"],
        toChains: ["Gnosis"],
        supportedTokens: ["ETH", "USDC", "USDT", "DAI"],
        transferSpeed: "5-10 mins",
        fee: "0.05%",
        link: "https://bridge.gnosischain.com",
        defillamaSlug: null,
        bridgeType: "Lock-Mint",
        staticTvl: "$15M",
        staticVolume24h: "$2M",
    },
    {
        id: "42",
        name: "Omo Swap",
        status: "active",
        fromChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Arbitrum"],
        toChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Arbitrum"],
        supportedTokens: ["ETH", "USDC", "USDT", "O3"],
        transferSpeed: "12-28 mins",
        fee: "0.12% - 0.28%",
        link: "https://app.omoswap.xyz/",
        defillamaSlug: null,
        bridgeType: "Lock-Mint",
        staticTvl: "$2M",
        staticVolume24h: "$0.0004M",
    },
    {
        id: "43",
        name: "Carrier",
        status: "active",
        fromChains: ["Ethereum", "Solana", "BSC", "Polygon"],
        toChains: ["Ethereum", "Solana", "BSC", "Polygon"],
        supportedTokens: ["ETH", "SOL", "USDC", "USDT"],
        transferSpeed: "5-15 mins",
        fee: "0.1% - 0.2%",
        link: "https://www.carrier.so",
        defillamaSlug: null,
        bridgeType: "Lock-Mint",
        staticTvl: "$30M",
        staticVolume24h: "$1M",
    },
    {
        id: "44",
        name: "Cross-Chain Bridge",
        status: "active",
        fromChains: ["Ethereum", "BSC", "Polygon"],
        toChains: ["Ethereum", "BSC", "Polygon"],
        supportedTokens: ["ETH", "USDC", "USDT"],
        transferSpeed: "10-30 mins",
        fee: "0.1% - 0.2%",
        link: "https://app.crosschainbridge.org",
        defillamaSlug: "crosschain-bridge",
        bridgeType: "Lock-Mint",
        staticTvl: "$15M",
        staticVolume24h: "$0.5M",
    },
    {
        id: "45",
        name: "TON Bridge",
        status: "active",
        fromChains: ["Ethereum", "TON"],
        toChains: ["Ethereum", "TON"],
        supportedTokens: ["ETH", "USDC", "TON"],
        transferSpeed: "10-30 mins",
        fee: "0.05% - 0.15%",
        link: "https://bridge-v3.ton.org",
        defillamaSlug: null,
        bridgeType: "Lock-Mint",
        staticTvl: "$50M",
        staticVolume24h: "$1M",
    },
    {
        id: "46",
        name: "LayerSwap",
        status: "active",
        fromChains: ["Ethereum", "BSC", "Polygon", "Solana"],
        toChains: ["Ethereum", "BSC", "Polygon", "Solana"],
        supportedTokens: ["ETH", "USDC", "USDT", "SOL"],
        transferSpeed: "5-20 mins",
        fee: "0.05% - 0.15%",
        link: "https://layerswap.io",
        defillamaSlug: null,
        bridgeType: "Lock-Mint",
        staticTvl: "$140M",
        staticVolume24h: "$4M",
    },
    {
        id: "47",
        name: "Owlto Finance",
        status: "active",
        fromChains: ["Ethereum", "Arbitrum", "Optimism", "Base"],
        toChains: ["Ethereum", "Arbitrum", "Optimism", "Base"],
        supportedTokens: ["ETH", "USDC", "USDT"],
        transferSpeed: "3-10 mins",
        fee: "0.05% - 0.15%",
        link: "https://owlto.finance/",
        defillamaSlug: null,
        bridgeType: "Intent-Based",
        staticTvl: "$200M",
        staticVolume24h: "$10M",
    },

    {
        id: "48",
        name: "Squid",
        status: "active",
        fromChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Arbitrum"],
        toChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Arbitrum"],
        supportedTokens: ["ETH", "USDC", "USDT", "DAI"],
        transferSpeed: "3-10 mins",
        fee: "0.05% - 0.15%",
        link: "https://app.squidrouter.com/",
        defillamaSlug: null,
        bridgeType: "Intent-Based",
        staticTvl: "$100M",
        staticVolume24h: "$2M",
    },

    {
        id: "49",
        name: "Brid",
        status: "active",
        fromChains: ["Ethereum"],
        toChains: ["Base"],
        supportedTokens: ["ETH", "USDC", "USDT"],
        transferSpeed: "10 mins",
        fee: "0.05%",
        link: "https://brid.gg",
        defillamaSlug: null,
        bridgeType: "Lock-Mint",
        staticTvl: "$2.8B",
        staticVolume24h: "$0.8M",
    },

    
    // ─── Priority 4: Inactive bridges ──────────────────────────────────────────
{
        id: "50", 
        name: "Wrap Protocol",
        status: "inactive",
        fromChains: ["Ethereum", "Tezos"],
        toChains: ["Ethereum", "Tezos"],
        supportedTokens: ["ETH", "XTZ", "USDC"],
        transferSpeed: "10-25 mins",
        fee: "0.1% - 0.25%",
        link: "https://www.benderlabs.io/wrap",
        defillamaSlug: null,
        bridgeType: "Lock-Mint",
        staticTvl: "$150M",
        staticVolume24h: "$4M",
    },
    {
        id: "51",
        name: "Altitude", 
        status: "inactive",
        fromChains: ["Ethereum", "Avalanche", "Polygon"],
        toChains: ["Ethereum", "Avalanche", "Polygon"],
        supportedTokens: ["ETH", "USDC", "USDT"],
        transferSpeed: "5-15 mins",
        fee: "0.06% - 0.12%",
        link: "https://altitude.fi",
        defillamaSlug: null,
        bridgeType: "Lock-Mint",
        staticTvl: "$50M",
        staticVolume24h: "$1M",
    },
    {
        id: "52",
        name: "Multichain",
        status: "inactive",
        fromChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Fantom"],
        toChains: ["Ethereum", "BSC", "Polygon", "Avalanche", "Fantom"],
        supportedTokens: ["ETH", "USDC", "USDT", "DAI", "BTC"],
        transferSpeed: "10-20 mins",
        fee: "0.1% - 0.3%",
        link: "https://multichain.org",
        defillamaSlug: null,
        bridgeType: "Lock-Mint",
        staticTvl: "$0",
        staticVolume24h: "$0",
    },
    {
        id: "53",
        name: "Nomad",
        status: "inactive",
        fromChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon"],
        toChains: ["Ethereum", "Arbitrum", "Optimism", "Polygon"],
        supportedTokens: ["ETH", "USDC", "DAI"],
        transferSpeed: "3-12 mins",
        fee: "0.03% - 0.1%",
        link: "https://nomad.xyz",
        defillamaSlug: null,
        bridgeType: "Lock-Mint",
        staticTvl: "NIL",
        staticVolume24h: "NIL",
    },
    {
        id: "54",
        name: "Socket Tech",
        status: "inactive",
        fromChains: ["Ethereum", "Arbitrum", "Optimism", "Base", "zkSync"],
        toChains: ["Ethereum", "Arbitrum", "Optimism", "Base", "zkSync"],
        supportedTokens: ["ETH", "USDC", "USDT", "DAI"],
        transferSpeed: "2-10 mins",
        fee: "0.05% - 0.12%",
        link: "https://www.socket.tech",
        defillamaSlug: null,
        bridgeType: "Intent-Based",
        staticTvl: "NIL",
        staticVolume24h: "NIL",
    },
    {
        id: "55",
        name: "Hashport",
        status: "inactive",
        fromChains: ["Ethereum", "Polygon", "Avalanche", "Cardano"],
        toChains: ["Ethereum", "Polygon", "Avalanche", "Cardano"],
        supportedTokens: ["ETH", "USDC", "ADA"],
        transferSpeed: "10-20 mins",
        fee: "0.1% - 0.25%",
        link: "https://app.hashport.network/",
        defillamaSlug: null,
        bridgeType: "Lock-Mint",
        staticTvl: "NIL",
        staticVolume24h: "NIL",
    },
    {
        id: "56",
        name: "Outerbridge",
        status: "inactive",
        fromChains: ["Ethereum", "BSC", "Polygon"],
        toChains: ["Ethereum", "BSC", "Polygon"],
        supportedTokens: ["ETH", "USDC", "USDT"],
        transferSpeed: "5-15 mins",
        fee: "0.08% - 0.18%",
        link: "https://outerbridge.io/",
        defillamaSlug: null,
        bridgeType: "Lock-Mint",
        staticTvl: "NIL",
        staticVolume24h: "NIL",
    },




]

// Derived counts — used by market-summary route
export const BRIDGE_COUNTS = {
    total: BRIDGE_CONFIG.length,
    active: BRIDGE_CONFIG.filter((b) => b.status === "active").length,
    paused: BRIDGE_CONFIG.filter((b) => b.status === "paused").length,
    inactive: BRIDGE_CONFIG.filter((b) => b.status === "inactive").length,
}